# Generated by Django 2.1 on 2020-09-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_bookinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceshi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.BooleanField(default=False)),
                ('addr', models.TextField()),
                ('age', models.IntegerField(default=0)),
                ('createTime', models.DateTimeField(db_column='pub_date')),
                ('addTime', models.DateTimeField(default=False)),
            ],
        ),
    ]
